### ISSUE TITLE
Transactional bank testcase with linearizability checking

### ISSUE THREAD

**Issue by PatrickHuang888** [siddontang/chaos#1]
Hi,
I have read the bank test case code,  it randomly mix with query and transactional 2 queries and updates operations. In my understanding this is a test case with transaction isolation semantics. and then check the history  events by linearizability checking.
My question is what is this transactional test case related to  linearizability? In what circumstance tidb  transaction allied with linearizability?

Thanks
Patrick

**Comment by siddontang** [comment]
Here we test SSI, and it must be linearizability.

**Comment by PatrickHuang888** [comment]
which means tidb default isolation level is SSI, right?

**Comment by siddontang** [comment]
No, TiDB default isolation is SI, so here for test, we need to use `select for update` to forcibly support SSI.

**Comment by PatrickHuang888** [comment]
good
