### ISSUE TITLE
Why tidb, tikv and pd are deployed on every node?

### ISSUE THREAD

**Issue by sydnever** [siddontang/chaos#15]
Does the frame require that every node should be equal to others?

Could I put only put tidb in node1 and node2, tikv in node3 and node4, and pd in node5?

**Comment by sydnever** [comment]
And why the number of nodes is five?

**Comment by siddontang** [comment]
all are derived from Jepsen. 

mostly, must equal to others.

**Comment by sydnever** [comment]
rrrrr, this framework has too many limits.
